diff --git i/Dockerfile w/Dockerfile
index b72d258..03e2025 100644
--- i/Dockerfile
+++ w/Dockerfile
@@ -48,4 +48,4 @@ COPY --from=build ${app_dir} ${app_dir}
 # TODO: change back after TypeScript migration
 #COPY --from=build ${app_dir}/dist ${app_dir}/dist
 
-CMD ["node", "."]
+CMD ["node", "--inspect=0.0.0.0:9230", "."]
