diff --git i/Dockerfile w/Dockerfile
index 3e08c61..4cc3c7a 100644
--- i/Dockerfile
+++ w/Dockerfile
@@ -9,6 +9,8 @@ ARG app_dir
 
 WORKDIR ${app_dir}
 
+RUN go install github.com/go-delve/delve/cmd/dlv@latest
+
 RUN --mount=type=cache,target=/go/pkg/mod/ \
 	--mount=type=bind,source=go.sum,target=go.sum \
 	--mount=type=bind,source=go.mod,target=go.mod \
@@ -17,7 +19,7 @@ RUN --mount=type=cache,target=/go/pkg/mod/ \
 COPY . .
 ARG BUILD_STRING=pretendo.pikmin3.docker
 RUN --mount=type=cache,target=/go/pkg/mod/ \
-	CGO_ENABLED=0 go build -ldflags "-X 'main.serverBuildString=${BUILD_STRING}'" -v -o ${app_dir}/build/server
+	CGO_ENABLED=0 go build -gcflags "all=-N -l" -ldflags "-X 'main.serverBuildString=${BUILD_STRING}'" -v -o ${app_dir}/build/server
 
 
 # * Running the final application
@@ -31,6 +33,7 @@ RUN mkdir -p ${app_dir}/log && chown go:go ${app_dir}/log
 
 USER go
 
+COPY --from=build /go/bin/dlv ${app_dir}/dlv
 COPY --from=build ${app_dir}/build/server ${app_dir}/server
 
-CMD [ "./server" ]
+CMD ["./dlv", "exec", "./server", "--listen=:2345", "--headless", "--api-version=2", "--log", "--accept-multiclient", "--continue"]
