diff --git i/Dockerfile w/Dockerfile
index a810a90..49d3fa5 100644
--- i/Dockerfile
+++ w/Dockerfile
@@ -1,16 +1,14 @@
-FROM node:18-alpine
+FROM node:20-alpine
 
-RUN apk add --no-cache python3 make gcc g++ 
 WORKDIR /app
 
-COPY "docker/entrypoint.sh" ./
-
 COPY package*.json ./
-RUN npm install bcrypt && npm rebuild bcrypt --build-from-source
 RUN npm install
 
 COPY . ./
+RUN npm run build
+RUN node generate-keys.js nex datastore
 
-VOLUME [ "/app/config.json", "/app/certs" ]
+VOLUME [ "/app/certs" ]
 
-CMD ["sh", "entrypoint.sh"]
+CMD ["node", "--inspect=0.0.0.0:9229", "./dist/server.js"]
