diff --git i/Dockerfile w/Dockerfile
index fb8db39..93b708b 100644
--- i/Dockerfile
+++ w/Dockerfile
@@ -9,6 +9,8 @@ ARG app_dir
 
 WORKDIR ${app_dir}
 
+RUN go install github.com/go-delve/delve/cmd/dlv@latest
+
 RUN --mount=type=cache,target=/go/pkg/mod/ \
 	--mount=type=bind,source=go.sum,target=go.sum \
 	--mount=type=bind,source=go.mod,target=go.mod \
@@ -16,7 +18,7 @@ RUN --mount=type=cache,target=/go/pkg/mod/ \
 
 COPY . .
 RUN --mount=type=cache,target=/go/pkg/mod/ \
-	CGO_ENABLED=0 go build -v -o ${app_dir}/build/server
+	CGO_ENABLED=0 go build -gcflags "all=-N -l" -v -o ${app_dir}/build/server
 
 
 # * Running the final application
@@ -32,4 +34,4 @@ USER go
 
 COPY --from=build ${app_dir}/build/server ${app_dir}/server
 
-CMD [ "./server" ]
+CMD ["./dlv", "exec", "./server", "--listen=:2345", "--headless", "--api-version=2", "--log", "--accept-multiclient", "--continue"]
