diff --git a/Dockerfile b/Dockerfile
index fb8db39..7817e6a 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -9,6 +9,8 @@ ARG app_dir
 
 WORKDIR ${app_dir}
 
+RUN go install github.com/go-delve/delve/cmd/dlv@latest
+
 RUN --mount=type=cache,target=/go/pkg/mod/ \
 	--mount=type=bind,source=go.sum,target=go.sum \
 	--mount=type=bind,source=go.mod,target=go.mod \
@@ -16,7 +18,7 @@ RUN --mount=type=cache,target=/go/pkg/mod/ \
 
 COPY . .
 RUN --mount=type=cache,target=/go/pkg/mod/ \
-	CGO_ENABLED=0 go build -v -o ${app_dir}/build/server
+	CGO_ENABLED=0 go build -v -o ${app_dir}/build/server -gcflags "all=-N -l"
 
 
 # * Running the final application
@@ -30,6 +32,7 @@ RUN mkdir -p ${app_dir}/log && chown go:go ${app_dir}/log
 
 USER go
 
+COPY --from=build /go/bin/dlv ${app_dir}/dlv
 COPY --from=build ${app_dir}/build/server ${app_dir}/server
 
-CMD [ "./server" ]
+CMD ["./dlv", "exec", "./server", "--listen=:2346", "--headless", "--api-version=2", "--log", "--accept-multiclient", "--continue"]
